-- Restore full Shopify product descriptions: paragraph copy, Key Features,
-- and Package Contents for every listing. Adds two new columns and backfills
-- content for all products (kohli-rcb keeps its existing story — it never had
-- a Shopify listing to restore from).

alter table public.products add column if not exists features text[] not null default '{}';
alter table public.products add column if not exists package_contents text[] not null default '{}';

update public.products set story = 'Introduce your little ones to the enchanting world of Indian epics with our captivating Wooden Peg Dolls set. This specially designed kids edition features three beloved deities: Ganesha, Shiva, and Parvati. Crafted from child-friendly wood, this set includes six engaging story cards that narrate the exciting life adventures of Lord Ganesha. Spark your child''s imagination, inspire creativity, and instill cultural appreciation with these adorable peg dolls.', features = ARRAY['Child-friendly design', 'Premium quality', 'Hand-painted', 'Educational and interactive', 'Interactive story cards', 'Perfect gift'], package_contents = ARRAY['1 x Ganesha wooden peg doll', '1 x Shiva wooden peg doll', '1 x Parvati wooden peg doll', '6 x Ganesha''s Life Adventure story cards'], material = 'Hand-painted wood, cotton pouch, story cards included, height 4 inches (each doll)' where id = 'ganesha-combo';
update public.products set story = 'Discover the enchanting world of Krishna, Sudama, and Radha with our delightful Wooden Peg Doll Set. This charming trio of hand-painted wooden dolls brings to life the timeless tales of friendship, devotion, and love, captivating both kids and adults alike. Krishna, the mischievous and divine Lord, is portrayed in his classic attire, complete with his iconic flute. Sudama, his humble and devoted friend, stands by his side, showcasing the beauty of their unwavering bond. Radha, the embodiment of love and devotion, adds a touch of elegance to the set.', features = ARRAY['Child-friendly design', 'Premium quality', 'Hand-painted', 'Educational and interactive', 'Perfect gift'], package_contents = ARRAY['1 x Krishna wooden peg doll', '1 x Radha wooden peg doll', '1 x Sudama wooden peg doll'], material = 'Hand-painted wood, height 4 inches (each doll)' where id = 'krishna-radha-sudama';
update public.products set story = 'Introduce the captivating tales of the Indian epic Ramayana to kids with our beautifully crafted Wooden Peg Dolls set. This enchanting set includes four intricately designed peg dolls representing the iconic characters of Rama, Sita, Laxman, and Hanuman, along with nine accompanying story cards. Each peg doll is hand-painted and made from high-quality wood, ensuring durability and a timeless aesthetic.', features = ARRAY['Exquisite design', 'Premium quality', 'Hand-painted', 'Educational and interactive', 'Versatile playtime', 'Perfect gift'], package_contents = ARRAY['1 x Rama wooden peg doll', '1 x Sita wooden peg doll', '1 x Laxman wooden peg doll', '1 x Hanuman wooden peg doll', '9 x Story cards', '1 x Cotton pouch'], material = 'Hand-painted wood, cotton pouch, story cards included, height 4 inches (each doll)' where id = 'ramayana-combo';
update public.products set story = 'Beautifully hand-crafted and painted wooden lattu that spin smoothly and keep kids entertained for hours. Made from high-quality wood with vibrant colours and a classic finish. Perfect for return gifts, party favors, traditional games, and nostalgic fun for all ages.', features = '{}', package_contents = '{}', material = 'Hand-painted wood, pack of 5' where id = 'lattu-spin-pack';
update public.products set story = 'Celebrate the beautiful bond of love, protection, and togetherness with our Handmade Rakhi Set of 3. Thoughtfully designed and handcrafted, these elegant rakhis are perfect for celebrating Raksha Bandhan with your brothers and loved ones. Crafted with care, each rakhi reflects the warmth of Indian traditions while adding a touch of simplicity and charm to your celebrations.', features = ARRAY['Set of 3 handcrafted rakhis', 'Elegant and festive designs', 'Comfortable to wear', 'Thoughtfully crafted for Raksha Bandhan celebrations', 'Ideal for gifting or family celebrations'], package_contents = ARRAY['3 × Handmade Rakhi'], material = 'Premium threads and decorative embellishments, pack of 3' where id = 'rakhi-set-pack-3';
update public.products set story = 'Celebrate the blessings of Lord Ganesha and the joy of Raksha Bandhan with this thoughtfully curated festive gift set. Featuring our hand-painted Ganesha, Shiva, and Parvati Wooden Peg Dolls along with three beautifully crafted Rakhis, this special edition is a meaningful way to celebrate love, family, and togetherness.', features = ARRAY['Hand-painted Ganesha, Shiva, and Parvati wooden peg dolls', 'Includes 3 festive Rakhis', 'Encourages storytelling and imaginative play', 'Introduces children to Indian culture and traditions', 'Child-friendly and non-toxic materials'], package_contents = ARRAY['1 × Ganesha wooden peg doll', '1 × Shiva wooden peg doll', '1 × Parvati wooden peg doll', '3 × Rakhi'], material = 'Hand-painted wood, 3 rakhis included, height 4 inches (each doll)' where id = 'ganesha-rakhi-set';
update public.products set story = 'Celebrate the beautiful bond of love, friendship, and protection with our special Raksha Bandhan Edition. This thoughtfully curated gift set brings together our hand-painted Krishna, Radha, and Sudama Wooden Peg Dolls along with three beautifully crafted Rakhis, making it a meaningful way to celebrate the festival with siblings and loved ones.', features = ARRAY['Hand-painted wooden peg dolls', 'Includes 3 festive Rakhis', 'Celebrates Indian culture and traditions', 'Encourages storytelling and imaginative play', 'Child-friendly and non-toxic materials'], package_contents = ARRAY['1 × Krishna wooden peg doll', '1 × Radha wooden peg doll', '1 × Sudama wooden peg doll', '3 × Rakhi'], material = 'Hand-painted wood, 3 rakhis included, height 4 inches (each doll)' where id = 'krishna-radha-sudama-rakhi-set';
update public.products set story = 'Celebrate the spirit of Raksha Bandhan with a gift that beautifully blends tradition, storytelling, and culture. This special Raksha Bandhan Edition features our hand-painted Ramayana Wooden Peg Dolls along with three beautifully crafted Rakhis, making it a meaningful keepsake for siblings and families.', features = ARRAY['Hand-painted Ramayana wooden peg dolls', 'Includes 3 festive Rakhis', 'Introduces children to the Ramayana through storytelling and imaginative play', 'Celebrates Indian culture and traditions', 'Child-friendly and non-toxic materials'], package_contents = ARRAY['1 × Ramayana wooden peg doll set', '3 × Rakhi'], material = 'Hand-painted wood, 3 rakhis included, height 4 inches (each doll)' where id = 'ramayana-rakhi-set';
update public.products set story = 'Celebrate the remarkable career of Indian cricketing legend Virat Kohli with our meticulously crafted Wooden Peg Doll. Standing at 6 inches tall, this collectible doll pays homage to the extraordinary achievements and charismatic persona of the cricketing superstar. Made from high-quality wood, this hand-painted peg doll is a must-have for cricket enthusiasts and fans of Virat.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for cricket enthusiasts'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'kohli';
update public.products set story = 'A red-and-gold tribute for RCB''s biggest fans — years of loyalty, finally on your shelf.', features = '{}', package_contents = '{}', material = 'Hand-painted wood' where id = 'kohli-rcb';
update public.products set story = 'Experience the essence of Rajni, the iconic Indian actor, through our meticulously crafted wooden figurine. Rajni''s charismatic presence and cinematic legacy are beautifully captured in this masterpiece. With intricate detailing, the figurine reflects his distinctive style and aura, making it a must-have for fans and collectors alike. Known for his larger-than-life persona, Rajni has left an indelible mark on Indian cinema with his powerful performances and unique charm.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for Rajni fans'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'rajni';
update public.products set story = 'Introducing our meticulously crafted wooden figurine capturing the essence of Modi Ji, the Prime Minister of India. Modi Ji''s charismatic leadership and transformative policies have made a significant impact on India''s socio-economic landscape. Our finely carved figurine pays homage to his dynamic persona — a tribute to visionary initiatives like "Make in India" and "Digital India" that have propelled India''s growth on the global stage.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for politics enthusiasts'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'modi-ji';
update public.products set story = 'Celebrate the electrifying talent of football sensation Mbappé with our meticulously handcrafted Wooden Peg Doll. Standing at 6 inches tall, this collectible captures the speed, confidence, and brilliance of one of the world''s most exciting football stars. Crafted from premium-quality wood and hand-painted with intricate details, this peg doll is a perfect keepsake for football lovers, collectors, and admirers of Mbappé''s remarkable journey.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for football enthusiasts'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'mbappe';
update public.products set story = 'Introducing the Chulbul Pandey Wooden Toy, a spirited addition to our enchanting collection of handcrafted wooden toys. Channel the charismatic energy of Salman Khan''s iconic character with this meticulously designed creation. Crafted with precision and infused with creativity, this wooden toy encapsulates the essence of fearless heroism and playful charm that defines Chulbul Pandey.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for Salman Khan fans'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'sallu-bhai';
update public.products set story = 'Celebrate the spirit of innovation with our Mini Coder Wooden Doll, a charming tribute to tech enthusiasts, developers, and digital dreamers. Standing at 6 inches tall, this handcrafted figurine is designed in the iconic minimalist peg-doll style, with smooth wooden detailing and a sleek matte finish. Dressed in a classic "CODE </>" tee and comfy black pants, this adorable character sports glasses and a friendly smile — making it a perfect desk companion or a thoughtful gift for coders and tech lovers alike.', features = ARRAY['Height: 6 inches', 'Premium wood with smooth painted finish', 'Hand-painted design with attention to detail', 'Perfect gift for programmers, tech teams, or startup swag', 'Great for office desks, shelves, or creative inspiration corners'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'coder-collectible';
update public.products set story = 'Celebrate the remarkable life of Dr. APJ Abdul Kalam — India''s Missile Man — with our meticulously crafted Wooden Peg Doll. Standing at 6 inches tall, this collectible doll pays homage to his extraordinary achievements and the humility for which he''s remembered. Made from high-quality wood, this hand-painted peg doll is a must-have for admirers of his life and legacy.', features = ARRAY['Lifelike representation', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for history and science enthusiasts'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'kalam-collectible';
update public.products set story = 'Celebrate everyone''s favorite web-slinger with our meticulously crafted Wooden Peg Doll. Standing at 6 inches tall, this hand-painted collectible captures the iconic mask, web pattern, and spirit of the world''s most beloved superhero. Made from high-quality wood, it''s a must-have for comic fans and collectors alike. This is a limited pre-book drop of 10 pieces — production begins once Batch 1 closes, and you''ll be notified once your piece ships.', features = ARRAY['Iconic superhero design', 'Premium quality', 'Hand-painted', 'Collector''s item', 'Ideal gift for comic and superhero fans'], package_contents = '{}', material = 'Hand-painted wood, height 6 inches' where id = 'spidey-collectible';
